# Generated by Django 2.0.2 on 2018-05-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='ip_address',
        ),
    ]
