# Generated by Django 2.0.2 on 2018-05-26 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0004_auto_20180526_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
