# Generated by Django 2.0.2 on 2018-05-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0005_auto_20180526_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
