# Generated by Django 2.0.2 on 2018-07-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0007_auto_20180526_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('subject', models.CharField(max_length=256)),
                ('contact_date', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
