# Generated by Django 2.0.2 on 2018-07-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0008_auto_20180714_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startYear', models.CharField(default='NOW', max_length=4, verbose_name='start year')),
                ('startMonth', models.CharField(default='NOW', max_length=2, verbose_name='start month')),
                ('startDate', models.CharField(default='NOW', max_length=2, verbose_name='start date')),
                ('endYear', models.CharField(default='NOW', max_length=4, verbose_name='end year')),
                ('endMonth', models.CharField(default='NOW', max_length=2, verbose_name='end month')),
                ('endDate', models.CharField(default='NOW', max_length=2, verbose_name='end date')),
            ],
        ),
    ]
