# Generated by Django 2.0.2 on 2018-07-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0009_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days',
            name='endDate',
            field=models.CharField(default='N', max_length=2, verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='days',
            name='endMonth',
            field=models.CharField(default='N', max_length=2, verbose_name='end month'),
        ),
        migrations.AlterField(
            model_name='days',
            name='endYear',
            field=models.CharField(default='N', max_length=4, verbose_name='end year'),
        ),
        migrations.AlterField(
            model_name='days',
            name='startDate',
            field=models.CharField(default='N', max_length=2, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='days',
            name='startMonth',
            field=models.CharField(default='N', max_length=2, verbose_name='start month'),
        ),
        migrations.AlterField(
            model_name='days',
            name='startYear',
            field=models.CharField(default='N', max_length=4, verbose_name='start year'),
        ),
    ]
