# Generated by Django 2.0.2 on 2018-07-21 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0010_auto_20180721_1740'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='days',
            unique_together={('startYear', 'startMonth', 'startDate', 'endYear', 'endMonth', 'endDate')},
        ),
    ]
