# Generated by Django 2.0.2 on 2019-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0011_auto_20180721_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='description'),
        ),
    ]
